### ISSUE TITLE
Add metric for volume storage size

### ISSUE THREAD

**Issue by zackman0010** [containers/prometheus-podman-exporter#50]
I'd like to be able to monitor the amount of storage currently being utilized by my volumes. Looks like this data should be available:
Command line: `podman system df -v`
API: https://docs.podman.io/en/latest/_static/api.html#tag/system/operation/SystemDataUsageLibpod
https://github.com/containers/prometheus-podman-exporter/blob/38ae02876323cc60759979d4f2c96ed78c1e4228/vendor/github.com/containers/podman/v4/pkg/domain/entities/engine_container.go#L95

**Comment by navidys** [comment]
I am in same page as @ingobecker , on heavy system scraping disk usage will take a bit time.

**Comment by zackman0010** [comment]
Ouch, I didn't realize that's how that worked. Thank you, I'll find another way to get this data!

**Comment by megla-tlanghorst** [comment]
Doesn't the `local` driver work with subvolumes (like docker which uses zfs or btrfs subvolumes) or is RedHat behind on the ecosystem again and just uses random directories? The podman documentation is sadly no help at all as always... Because if it does, it should be easy and efficient to tell the size of the subvolume as it's being kept by the fs for quotas and such.

**Comment by navidys** [comment]
Hi @megla-tlanghorst 

As far as I know podman supports btrfs and zfs driver for storage which you can define under storage.conf 

https://www.jwillikers.com/podman-with-btrfs-and-zfs
